using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Webshop2_TeamG.Helpers
{
    internal class Gfx
    {
        public static void ColorIni()
        {
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.BackgroundColor = ConsoleColor.DarkBlue;
        }
        public static void WinIni()
        {
            ColorIni();
            int winWidth = 200;
            int winHeight = 50;
            Console.SetWindowSize(winWidth, winHeight);
            Console.SetBufferSize(winWidth, winHeight);
            Console.CursorVisible = false;
        }
        public static void Frontend(int gfxLeft, int gfxTop)
        {
            Console.SetCursorPosition(gfxLeft, gfxTop + 0);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 1);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 2);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄▀▀▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄▀▀▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▀▀█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄▀▀▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▀▀█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄▀▀▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄▀▀▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▀▀█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄▀▀▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("███▒▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒▒█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 3);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▀▀█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▄▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▄▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▄▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▄▄█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▀█▀█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▄▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▄▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("██▒▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 4);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("██▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 5);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▀▀▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▀▀▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▄▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("██▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 6);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("██▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 7);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄███══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 8);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 9);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 10);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 11);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("══════════════════════════════╣");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 12);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 13);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 14);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 15);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 16);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 17);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 18);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 19);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 20);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 21);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 22);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 23);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 24);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 25);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 26);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 27);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 28);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 29);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 30);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 31);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 32);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 33);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 34);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 35);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 36);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 37);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 38);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 39);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 40);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 41);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 42);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 43);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 44);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 45);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 46);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("███████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒▒");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 47);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("█▒▒▒");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("██████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("║");
            Console.ForegroundColor = (ConsoleColor)1;
            Console.BackgroundColor = (ConsoleColor)0;
            Console.Write("█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("▒▒▒█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 48);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)1;
            Console.Write("██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒║▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
            Console.SetCursorPosition(gfxLeft, gfxTop + 49);
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████");
            Console.ForegroundColor = (ConsoleColor)14;
            Console.BackgroundColor = (ConsoleColor)15;
            Console.Write("█");
        }

    }
}
